    version: '3.8'
    services:
      backend:
        build:
          context: .
          dockerfile: Dockerfile
        ports:
          - "3000:3000"
        depends_on:
          - frontend
      frontend:
        build:
          context: .
          dockerfile: Dockerfile.vue
        ports:
          - "8080:80"